// Package llmgen 은 LLM 으로 parsing rule 을 자동 생성하는 컴포넌트입니다.
//
// Package llmgen automatically generates parser_rules entries via LLM when a host
// has no rule registered (rule.ErrNoRule fallback path).
//
// 흐름:
//  1. parser_worker 가 rule.ErrNoRule 발견 → Generator.Enqueue 호출 (비동기 / 즉시 반환)
//  2. Generator goroutine: in-flight dedup 후 LLM 프롬프트 생성 → Provider.Generate 호출
//  3. 응답 JSON 파싱 → model.SelectorMap 으로 변환
//  4. validation: 생성된 selector 로 실제 HTML 매칭 확인 (0건이면 폐기)
//  5. ParserRuleRepository.Insert (enabled=true — CSS selector 검증 통과가 품질 게이트)
//  6. Resolver.Invalidate 로 negative cache flush — 다음 fetch 부터 새 rule 사용 가능
//
// 현재 구현 범위:
//   - 단일 LLM 호출 + 기본 validation + DB INSERT + cache invalidate
//   - Best-effort in-process dedup (단일 instance 보호)
//
// 후속 확장 후보:
//   - 비용 cap (일일 / 시간당 호출 수 제한)
//   - audit log + Prometheus metric
//   - 분산 dedup (Redis lock)
package llmgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/PuerkitoBio/goquery"

	"issuetracker/internal/processor/fetcher/core"
	"issuetracker/internal/processor/parser/rule"
	"issuetracker/internal/storage"
	"issuetracker/internal/storage/model"
	"issuetracker/internal/storage/primitive"
	"issuetracker/internal/storage/repository"
	"issuetracker/pkg/llm"
	"issuetracker/pkg/llm/prompt"
	"issuetracker/pkg/logger"
)

// LLMAutoSourceName 은 LLM 으로 자동 생성된 rule row 의 source_name 값입니다.
// 운영 대시보드 / 운영자 review 시 hand-tuned rule 과 구분 가능.
//
// 외부 패키지 (예: parser_worker 의 sample 누적) 도 본 상수를 사용 —
// 동기화 누락 방지.
const LLMAutoSourceName = "llm-auto"

// llmAutoDescription 은 자동 생성 row 의 description prefix 입니다.
const llmAutoDescription = "auto-generated by llmgen — review before enabling"

// pendingQueueOpTimeout 은 PendingQueue Redis 호출의 individual deadline 입니다.
// Redis stall 시 background goroutine 의 defer Release 가 막혀 host-level inflight lock 이
// 영구 stuck 되는 것을 방지 — 짧은 timeout 으로 fast-fail.
const pendingQueueOpTimeout = 2 * time.Second

// SelectorValidator 는 생성된 셀렉터의 의미 검증 인터페이스입니다.
// DOM 매칭 검증 이후 추가 단계로 실행 — 추출 내용이 실제 뉴스 제목/본문인지 LLM 으로 확인.
// nil 이면 의미 검증 건너뜀 (DOM 검증만 수행).
type SelectorValidator interface {
	Validate(ctx context.Context, html string, selectors model.SelectorMap, targetType model.TargetType) (SelectorValidatorResult, error)
}

// SelectorValidatorResult 는 의미 검증 결과입니다.
type SelectorValidatorResult struct {
	Valid  bool
	Reason string
}

// SelectorExtractor 는 HTML 에서 CSS 셀렉터를 추출하는 인터페이스입니다.
//
// 기본 구현: pkg/llm.Provider 기반 LLM 호출 (Gemini Flash 등).
// 대체 구현: claudegen.ClaudeWorker (Claude Code 웜 컨테이너).
// SetExtractor 로 교체하면 추출 단계만 대체되고 나머지 흐름 (validation, INSERT) 은 동일.
type SelectorExtractor interface {
	Extract(ctx context.Context, host string, targetType model.TargetType, html string) (model.SelectorMap, error)
}

// modelNamer 는 추출기가 사용하는 모델 ID 를 반환하는 선택적 인터페이스입니다.
// SelectorExtractor 구현체가 이 인터페이스도 구현하면 실제 모델 ID 를 DB description 에 기록합니다.
// 구현하지 않으면 fallback "claude-code" 를 사용합니다.
type modelNamer interface {
	ModelName() string
}

// selectorValidationError 는 validateSelectors 실패를 나타내는 sentinel 타입입니다.
// Enqueue goroutine 에서 다른 에러 (LLM API 실패, JSON 파싱 실패 등) 와 구분하여
// validate 실패일 때만 validateFailureHandler 를 호출하기 위해 사용합니다.
type selectorValidationError struct{ cause error }

func (e *selectorValidationError) Error() string {
	return "validate generated selectors: " + e.cause.Error()
}
func (e *selectorValidationError) Unwrap() error { return e.cause }

// errBlacklistedNoRule 는 EnrichedExtractor 가 페이지를 blacklist 로 판정해 셀렉터 INSERT 를
// skip 한 경우 runOnce 가 반환하는 sentinel error 입니다 (CodeRabbit Major 반영).
//
// 본 에러는 Enqueue goroutine 에서 정상 분기 (룰 생성 성공 → pendingQueue.Flush) 와 구분
// 하기 위한 전용 신호. blacklist 로 판정된 host 는 새 룰이 없으므로 pending 큐에 쌓인 URL
// 들도 fetch 시 ErrNoRule 로 다시 LLM 호출 → 또 blacklist → 무한 루프 발생을 방지하기 위해
// pendingQueue flush 를 skip.
//
// 호출자는 errors.Is 로 식별 — 다른 에러 (LLM API 실패, JSON 파싱 등) 와 분리.
var errBlacklistedNoRule = errors.New("llmgen: page blacklisted, no rule generated")

// Generator 는 host 별 parsing rule 을 LLM 으로 자동 생성합니다.
//
// goroutine-safe — provider / repo / resolver 가 자체 thread-safety 를 가짐.
// locker 는 InflightLocker 구현체에 따라 자체 thread-safety 를 가짐.
//
// Lifecycle:
//   - Enqueue 가 background goroutine 으로 LLM 호출 수행 — sync.WaitGroup 으로 추적
//   - Stop(ctx) 호출 시 새 Enqueue 차단 + 진행 중 goroutine 의 완료 대기 (graceful shutdown)
//   - Stop 후 Enqueue 는 noop (race 안전)
type Generator struct {
	provider     llm.Provider
	extractor    SelectorExtractor // nil 이면 provider 로 fallback
	repo         repository.ParserRuleRepository
	resolver     *rule.Resolver
	promptLoader prompt.Loader
	log          *logger.Logger

	// validateFailureHandler 는 selector 검증 실패 시 호출되는 콜백입니다.
	// 인자: (ctx, ref, llmRetryCount, targetType, crawlerName).
	//   - ref: raw *core.RawContent 의 경량 snapshot — goroutine 내 포인터 공유 없이 값 전달 (Copilot 피드백).
	//   - targetType, crawlerName: Kafka 메시지 헤더 복원에 필요 (gemini/Copilot/CodeRabbit 피드백).
	// background goroutine 에서 호출 — thread-safe 책임은 핸들러에 있음.
	// nil 이면 호출 안 함.
	validateFailureHandler func(context.Context, core.RawContentRef, int, model.TargetType, string)

	locker       primitive.InflightLocker // 기본: memInflightLocker, Redis 활성 시: RedisInflightLocker
	pendingQueue primitive.PendingQueue   // nil 이면 pending URL 보존 비활성
	requeueFn    RequeueFunc              // nil 이면 재투입 비활성
	semValidator SelectorValidator        // nil 이면 의미 검증 건너뜀
	blacklistSvc BlacklistAutoRegister    // nil 이면 자동 blacklist 등록 skip (#326). 이슈 #431 — repository 직접 의존 제거, service interface 로 추상화.
	breaker      *HostBreaker             // nil 이면 breaker 비활성 (이슈 #215)
	wg           sync.WaitGroup
	stopped      atomic.Bool
}

// SetValidateFailureHandler 는 selector 검증 실패 시 호출할 콜백을 등록합니다.
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetValidateFailureHandler(fn func(context.Context, core.RawContentRef, int, model.TargetType, string)) {
	g.validateFailureHandler = fn
}

// SetPendingQueue 는 대기 URL 큐와 재투입 콜백을 등록합니다.
// 둘 다 비-nil 이어야 활성화됩니다. Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로
// 초기화 시 1회만 호출합니다.
func (g *Generator) SetPendingQueue(pq primitive.PendingQueue, fn RequeueFunc) {
	g.pendingQueue = pq
	g.requeueFn = fn
}

// SetLocker 는 분산 Lock 구현체를 교체합니다.
// nil 이면 기본 in-process memInflightLocker 로 fallback.
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetLocker(l primitive.InflightLocker) {
	if l == nil {
		g.locker = primitive.NewMemInflightLocker()
		return
	}
	g.locker = l
}

// SetSelectorValidator 는 의미 검증기를 등록합니다.
// nil 이면 의미 검증 건너뜀. Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로
// 초기화 시 1회만 호출합니다.
func (g *Generator) SetSelectorValidator(v SelectorValidator) {
	g.semValidator = v
}

// SetExtractor 는 셀렉터 추출 단계를 교체합니다.
// nil 이면 기존 provider (Gemini Flash 등) 로 fallback.
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetExtractor(e SelectorExtractor) {
	g.extractor = e
}

// BlacklistAutoRegister 는 LLM blacklist 판정 결과를 자동 등록하는 최소 인터페이스입니다 (이슈 #431).
//
// storage/service.BlacklistService 가 본 인터페이스를 만족 — Generator 는 service 패키지를
// 직접 import 하지 않고 인터페이스만 의존 (의존성 역전).
type BlacklistAutoRegister interface {
	HandleLLMDecision(ctx context.Context, host, sampleURL string, targetType model.TargetType, reason string) (inserted bool, err error)
}

// SetBlacklistService 는 EnrichedExtractor 가 페이지를 blacklist 로 판정했을 때 등록할
// service 를 등록합니다 (이슈 #431, 기존 SetBlacklistRepo 대체). nil 이면 blacklist 자동 등록 skip —
// Generator 는 셀렉터 INSERT 만 skip 하고 다음 흐름 진행 (LLM retry 가능).
//
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetBlacklistService(svc BlacklistAutoRegister) {
	g.blacklistSvc = svc
}

// SetBreaker 는 host 단위 LLM rate_limit circuit breaker 를 등록합니다 (이슈 #215).
//
// 동작:
//   - Enqueue 시 b.Allow(host, type) == false 면 즉시 skip (cooldown 중)
//   - runOnce 결과의 wrap 된 *llm.Error 를 unwrap 하여:
//     · ErrCodeRateLimit → b.RecordRateLimit
//     · 그 외 / nil      → b.RecordSuccess
//
// nil 이면 breaker 비활성 — 기존 동작 유지 (모든 호출 그대로).
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetBreaker(b *HostBreaker) {
	g.breaker = b
}

// New 는 Generator 를 생성합니다.
//
// provider / repo / resolver / promptLoader / log 모두 비-nil 필수. 하나라도 nil 이면 error —
// 호출자 (cmd/main) 가 boot fatal 처리.
func New(provider llm.Provider, repo repository.ParserRuleRepository, resolver *rule.Resolver, promptLoader prompt.Loader, log *logger.Logger) (*Generator, error) {
	if provider == nil {
		return nil, errors.New("llmgen: New requires non-nil provider")
	}
	if repo == nil {
		return nil, errors.New("llmgen: New requires non-nil repo")
	}
	if resolver == nil {
		return nil, errors.New("llmgen: New requires non-nil resolver")
	}
	if promptLoader == nil {
		return nil, errors.New("llmgen: New requires non-nil promptLoader")
	}
	if log == nil {
		return nil, errors.New("llmgen: New requires non-nil log")
	}
	return &Generator{
		provider:     provider,
		repo:         repo,
		resolver:     resolver,
		promptLoader: promptLoader,
		log:          log,
		locker:       primitive.NewMemInflightLocker(),
	}, nil
}

// Enqueue 는 (host, type) 에 대한 LLM rule 생성을 비동기로 시작합니다.
//
// Enqueue starts an async generation attempt and returns immediately. raw 의 HTML 을
// LLM 프롬프트 입력으로 사용 — 호출자가 Enqueue 후 raw 를 폐기해도 안전하도록 필요 데이터를 캡쳐.
//
// llmRetryCount 는 호출자 (parser_worker) 가 RawContentRef 에서 전달하는 재큐 횟수입니다.
// crawlerName 은 Kafka 메시지 헤더 복원용 — validateSelectors 실패 시 재큐 메시지에 포함됩니다.
// jobTimeout 은 원본 crawl job 의 timeout — pending 재투입 시 카테고리 chained job timeout 보존.
// validateSelectors 실패 시 validateFailureHandler 가 등록되어 있으면
// (ctx, ref, llmRetryCount, targetType, crawlerName) 으로 호출됩니다.
//
// 동일 (host, type) 에 대한 in-flight 호출이 이미 있으면 즉시 skip.
// Stop 호출 후의 Enqueue 는 즉시 noop.
func (g *Generator) Enqueue(ctx context.Context, host string, targetType model.TargetType, raw *core.RawContent, llmRetryCount int, crawlerName string, jobTimeout time.Duration) {
	g.enqueueImpl(ctx, host, targetType, raw, llmRetryCount, crawlerName, jobTimeout, false)
}

// EnqueueStale 은 stale rule 재학습 모드로 LLM 호출을 비동기 시작합니다.
//
// 차이점 (vs Enqueue):
//   - pre-check 의 enabled=true 룰 적중 시 skip 안 함 — v2 학습 진행
//   - 마지막 INSERT 가 InsertNextVersion 사용 — 기존 v1 보존 + v2 추가
//
// 호출 시점: parser_worker 가 ErrParseFailure / ErrEmptySelector 임계 도달 시 호출.
// disabled 룰 잔존 host 는 운영자 의도 존중 — pre-check 에서 skip.
func (g *Generator) EnqueueStale(ctx context.Context, host string, targetType model.TargetType, raw *core.RawContent, llmRetryCount int, crawlerName string, jobTimeout time.Duration) {
	g.enqueueImpl(ctx, host, targetType, raw, llmRetryCount, crawlerName, jobTimeout, true)
}

// enqueueImpl 은 Enqueue / EnqueueStale 의 공통 구현입니다.
// stale=true 면 InsertNextVersion 경로 (v2 추가), false 면 기존 Insert 경로 (v1).
func (g *Generator) enqueueImpl(ctx context.Context, host string, targetType model.TargetType, raw *core.RawContent, llmRetryCount int, crawlerName string, jobTimeout time.Duration, stale bool) {
	if g.stopped.Load() {
		return
	}
	if raw == nil || raw.HTML == "" {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).Debug("llmgen enqueue skipped — empty raw")
		return
	}

	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return
	}

	// Host breaker (이슈 #215) — 동일 host 의 LLM 호출이 연속 rate_limit hit 한 상태이면
	// 즉시 skip 하여 quota 소비 회피. cooldown 만료 시 자동으로 다시 통과.
	if g.breaker != nil {
		if allowed, remaining := g.breaker.Allow(host, targetType); !allowed {
			g.log.WithFields(map[string]interface{}{
				"host":               host,
				"target_type":        string(targetType),
				"cooldown_remaining": remaining.String(),
			}).Info("llmgen enqueue skipped — host breaker cooldown")
			return
		}
	}

	// 필요한 데이터를 값으로 캡쳐 — goroutine 내 포인터 공유 없이 안전 (Copilot 피드백).
	htmlSnapshot := raw.HTML
	urlSnapshot := raw.URL
	rawRef := core.RawContentRef{
		ID:         raw.ID,
		URL:        raw.URL,
		FetchedAt:  raw.FetchedAt,
		SourceInfo: raw.SourceInfo,
	}

	// TryAcquire: WithoutCancel 후 timeout — 호출자 ctx cancel 이 즉시 전파되지 않도록 하되
	// Redis 장애 시 무기한 블록도 방지. 기존 inflightSet 동작(cancel 무시)과 일관성 유지.
	acquireCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 5*time.Second)
	acquired, err := g.locker.TryAcquire(acquireCtx, host, targetType)
	cancel()
	if err != nil {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).WithError(err).Warn("llmgen inflight lock acquire failed, skipping")
		return
	}
	if !acquired {
		// in-flight 중 — pending 큐에 적재하여 룰 생성 완료 후 재파싱.
		if g.pendingQueue != nil {
			item := PendingItem{
				RawRef:        rawRef,
				CrawlerName:   crawlerName,
				LLMRetryCount: llmRetryCount,
				TargetType:    targetType,
				TimeoutMs:     jobTimeout.Milliseconds(),
			}
			payload, mErr := json.Marshal(item)
			if mErr != nil {
				g.log.WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
				}).WithError(mErr).Warn("llmgen pending item marshal failed")
			} else {
				pushCtx, pushCancel := context.WithTimeout(context.WithoutCancel(ctx), pendingQueueOpTimeout)
				perr := g.pendingQueue.Push(pushCtx, host, targetType, payload)
				pushCancel()
				if perr != nil {
					g.log.WithFields(map[string]interface{}{
						"host":        host,
						"target_type": string(targetType),
					}).WithError(perr).Warn("llmgen pending queue push failed")
				} else {
					g.log.WithFields(map[string]interface{}{
						"host":        host,
						"target_type": string(targetType),
						"url":         rawRef.URL,
					}).Debug("llmgen enqueue deferred — added to pending queue")
				}
			}
		} else {
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
			}).Debug("llmgen enqueue skipped — in-flight request already exists")
		}
		return
	}

	// 호출자 ctx 의 cancel 은 무시 (best-effort 후속 작업) — trace ID 등 메타데이터 보존.
	bgCtx := context.WithoutCancel(ctx)

	g.wg.Add(1)
	go func() {
		defer g.wg.Done()
		defer func() {
			if rerr := g.locker.Release(bgCtx, host, targetType); rerr != nil {
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
				}).WithError(rerr).Warn("llmgen inflight lock release failed")
			}
		}()

		err := g.runOnce(bgCtx, host, targetType, urlSnapshot, htmlSnapshot, stale)

		// Host breaker (#215) state 갱신 — runOnce 결과에서 *llm.Error 를 unwrap 하여 분류.
		// rate_limit 만 RecordRateLimit, 그 외 (nil 포함) 는 RecordSuccess (회복 신호).
		if g.breaker != nil {
			var llmErr *llm.Error
			if errors.As(err, &llmErr) && llmErr.Code == llm.ErrCodeRateLimit {
				g.breaker.RecordRateLimit(host, targetType)
			} else {
				g.breaker.RecordSuccess(host, targetType)
			}
		}

		if err != nil {
			// blacklist sentinel 은 normal completion — pending flush skip 만 하고 logging 도 별도.
			if errors.Is(err, errBlacklistedNoRule) {
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
					"url":         urlSnapshot,
				}).Info("llmgen page blacklisted, pending flush skipped")
				return
			}

			logger.FromContext(bgCtx).WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
				"url":         urlSnapshot,
			}).WithError(err).Warn("llmgen rule generation failed")

			// selector 검증 실패인 경우에만 재큐 콜백 호출.
			// rawRef (값 복사) + targetType + crawlerName 전달 — 헤더 복원에 사용.
			var sve *selectorValidationError
			if errors.As(err, &sve) && g.validateFailureHandler != nil {
				g.validateFailureHandler(bgCtx, rawRef, llmRetryCount, targetType, crawlerName)
			}
			return
		}

		// 룰 생성 성공 — pending 대기 URL 을 파서 워커에 재투입.
		// flush 는 defer(Release) 실행 전에 수행됨 — flush 중 새로 들어온 URL 은 pending 에 적재되고
		// 락 해제 후 새 runOnce 가 다음 flush 에서 처리.
		// Kafka publish 실패 항목은 requeueFn 이 반환 → pending 에 재적재.
		if g.pendingQueue != nil && g.requeueFn != nil {
			flushCtx, flushCancel := context.WithTimeout(bgCtx, pendingQueueOpTimeout)
			payloads, ferr := g.pendingQueue.Flush(flushCtx, host, targetType)
			flushCancel()
			if ferr != nil {
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
				}).WithError(ferr).Warn("llmgen pending queue flush failed")
			} else if len(payloads) > 0 {
				items := make([]PendingItem, 0, len(payloads))
				for _, raw := range payloads {
					var item PendingItem
					if err := json.Unmarshal(raw, &item); err != nil {
						logger.FromContext(bgCtx).WithFields(map[string]interface{}{
							"host":        host,
							"target_type": string(targetType),
						}).WithError(err).Warn("llmgen pending payload unmarshal failed — dropping")
						continue
					}
					items = append(items, item)
				}
				failed := g.requeueFn(bgCtx, items)
				for _, item := range failed {
					payload, mErr := json.Marshal(item)
					if mErr != nil {
						logger.FromContext(bgCtx).WithFields(map[string]interface{}{
							"host":        host,
							"target_type": string(targetType),
							"url":         item.RawRef.URL,
						}).WithError(mErr).Warn("llmgen failed-item marshal failed")
						continue
					}
					rePushCtx, rePushCancel := context.WithTimeout(bgCtx, pendingQueueOpTimeout)
					perr := g.pendingQueue.Push(rePushCtx, host, targetType, payload)
					rePushCancel()
					if perr != nil {
						logger.FromContext(bgCtx).WithFields(map[string]interface{}{
							"host":        host,
							"target_type": string(targetType),
							"url":         item.RawRef.URL,
						}).WithError(perr).Warn("llmgen failed to re-push Kafka-failed pending item")
					}
				}
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
					"count":       len(items),
					"failed":      len(failed),
				}).Info("llmgen pending URLs requeued for parsing")
			}
		}
	}()
}

// Stop 은 새 Enqueue 를 차단하고 진행 중인 background goroutine 의 완료를 대기합니다 (graceful shutdown).
//
// ctx 가 cancel 되면 in-flight 호출 완료 대기를 중단하고 즉시 반환 — 단, 진행 중 goroutine
// 자체는 background ctx (WithoutCancel) 로 동작하므로 Stop 반환 후에도 LLM 호출은 계속 진행될 수 있음.
// 운영자가 진정한 hard stop 을 원하면 process kill 필요 (LLM 호출 자체 timeout 은 LLMConfig.Timeout 으로 제어).
//
// 호출자가 Stop 을 호출하기 전에 새 Enqueue source (parser worker) 가 먼저 정지되어야 함 —
// 그래야 Stop 이 반환된 시점에 모든 in-flight 호출이 정리되었음을 보장할 수 있음.
//
// Idempotent — 여러 번 호출되어도 안전 (두 번째 호출은 즉시 반환).
func (g *Generator) Stop(ctx context.Context) {
	if !g.stopped.CompareAndSwap(false, true) {
		return // 이미 Stop 호출됨
	}

	done := make(chan struct{})
	go func() {
		g.wg.Wait()
		close(done)
	}()

	select {
	case <-done:
		g.log.Info("llmgen generator stopped — all in-flight requests completed")
	case <-ctx.Done():
		g.log.Warn("llmgen generator stop timeout — in-flight LLM calls may still be running in background")
	}
}

// runOnce 는 단일 추출 + validation + INSERT + cache invalidate 의 동기 실행입니다.
// 호출자 (Enqueue 의 goroutine) 가 in-flight 슬롯 release 책임.
func (g *Generator) runOnce(ctx context.Context, host string, targetType model.TargetType, sampleURL, html string, stale bool) error {
	// 사전 lookup — 동일 자연키 룰이 이미 DB 에 존재하면 LLM 호출 회피.
	//
	//   - enabled=true 룰 적중 시에만 skip (resolver 가 enabled=TRUE 만 조회하므로 disabled 는 사실상 부재)
	//   - ErrNotFound 만 normal miss, 그 외 에러는 warn 로그 — DB 장애 silent fallthrough 회피
	//   - stale=true: v2 학습 진행 — pre-check enabled hit 분기에서 skip 안 함
	existing, err := g.repo.FindByNaturalKey(ctx, LLMAutoSourceName, host, "", targetType, 1)
	switch {
	case err == nil && existing != nil && existing.Enabled:
		if stale {
			// stale 재학습: v1 enabled 그대로 유지하면서 v2 추가 — pre-check 통과.
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
				"existing_v1": existing.ID,
			}).Info("llmgen stale relearn — proceeding to v2 generation (existing v1 preserved)")
		} else {
			g.resolver.Invalidate(host, targetType)
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
				"rule_id":     existing.ID,
			}).Info("llmgen pre-check hit — enabled rule already exists, skipping LLM call")
			return nil
		}
	case err == nil && existing != nil && !existing.Enabled:
		// 운영자가 disable 한 룰이 잔존 — 자동 재활성은 정책상 보수적으로 회피.
		// LLM 재호출도 결과적으로 ErrDuplicate 로 reject 될 것이므로 LLM 비용 절감 + 운영 가시성을 위해 skip + warn.
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
			"rule_id":     existing.ID,
		}).Warn("llmgen pre-check hit — disabled rule exists, skipping LLM call (manual re-enable required)")
		return nil
	case err != nil && !errors.Is(err, storage.ErrNotFound):
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).WithError(err).Warn("llmgen pre-check lookup failed — proceeding to LLM (best-effort)")
		// fallthrough 로 LLM 경로 진행 — 후속 Insert 도 동일 원인으로 실패할 수 있으나
		// best-effort 정책 유지 (DB 일시 장애가 rule 학습 파이프라인을 영구 차단하지 않도록).
	}

	var (
		selectors model.SelectorMap
		modelName string
		pageType  string // EnrichedExtractor 모드에서 채워짐. legacy 경로는 "" (미분류).
		article   bool   // EnrichedExtractor 가 분류한 article body 여부 (이슈 #423). 기본 false.
	)

	if g.extractor != nil {
		// EnrichedExtractor (claudegen multi-step) 우선 — type assertion 으로 자동 분기.
		if enriched, ok := g.extractor.(EnrichedExtractor); ok {
			res, err := enriched.ExtractEnriched(ctx, host, targetType, html)
			if err != nil {
				return fmt.Errorf("claude code extractor: %w", err)
			}
			// validity == "blacklist" 분기 — 셀렉터 INSERT skip + 자동 blacklist 등록.
			// errBlacklistedNoRule sentinel 반환 — 정상 룰 생성 분기와 구분되어 호출자가
			// pendingQueue flush 를 skip (무한 루프 방지).
			if res.Blacklist != nil {
				g.handleBlacklistDecision(ctx, host, sampleURL, targetType, res.Blacklist)
				return errBlacklistedNoRule
			}
			selectors = res.Selectors
			pageType = string(res.PageType)
			// list (target_type=list) 룰은 정의상 article body 가 아님 — 안전성을 위해 article=false 강제.
			// page 룰만 LLM 의 article 분류를 반영 (#423).
			if targetType == model.TargetTypePage {
				article = res.Article
			}
			if mn, ok := g.extractor.(modelNamer); ok {
				modelName = mn.ModelName()
			} else {
				modelName = "claude-code"
			}
		} else {
			// legacy SelectorExtractor — Blacklist 분기 없음, page_type 도 빈 문자열.
			sm, err := g.extractor.Extract(ctx, host, targetType, html)
			if err != nil {
				return fmt.Errorf("claude code extractor: %w", err)
			}
			selectors = sm
			if mn, ok := g.extractor.(modelNamer); ok {
				modelName = mn.ModelName()
			} else {
				modelName = "claude-code"
			}
		}
	} else {
		// 기존 LLM provider 경로 (Gemini Flash 등)
		system, user, bpErr := BuildPrompt(g.promptLoader, host, targetType, html)
		if bpErr != nil {
			return fmt.Errorf("build llmgen prompt: %w", bpErr)
		}
		resp, err := g.provider.Generate(ctx, llm.Request{
			Messages: []llm.Message{
				{Role: llm.RoleSystem, Content: system},
				{Role: llm.RoleUser, Content: user},
			},
			TaskHint: llm.TaskHintJSON,
		})
		if err != nil {
			return fmt.Errorf("llm provider call: %w", err)
		}
		if resp == nil || resp.Content == "" {
			return errors.New("llm returned empty response")
		}
		sm, err := parseSelectorMap(resp.Content)
		if err != nil {
			return fmt.Errorf("parse llm response: %w", err)
		}
		selectors = sm
		modelName = resp.Model
	}

	if err := validateSelectors(selectors, targetType, html); err != nil {
		return &selectorValidationError{cause: err}
	}

	// 의미 검증 — DOM 매칭 후 추출 내용이 실제로 뉴스 제목/본문인지 LLM 으로 확인.
	if g.semValidator != nil {
		res, verr := g.semValidator.Validate(ctx, html, selectors, targetType)
		if verr != nil {
			// API 오류 — best-effort: 검증 인프라 장애가 rule 생성을 막지 않도록 warn 로그만 남기고 계속.
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
			}).WithError(verr).Warn("semantic validator API error, proceeding without semantic validation")
		} else if !res.Valid {
			return &selectorValidationError{cause: fmt.Errorf("semantic validation failed: %s", res.Reason)}
		}
	}

	// 프로그래매틱 검증 — 각 selector 를 sample HTML 에 적용 후 hit_rate 계산.
	// hit_rate < confidenceThreshold 인 selector 는 nil 로 drop — 신뢰할 수 없는 selector 가
	// DB 에 들어가 하류 parser 가 빈 값 / 잘못된 값을 추출하지 않도록.
	// published_at 은 form 검증 (time.Parse) 통과 시에만 hit 로 카운트.
	confidence := ComputeFieldConfidence(selectors, html)
	selectors = ApplyConfidenceFilter(selectors, confidence)

	record := &model.ParserRuleRecord{
		SourceName:  LLMAutoSourceName,
		HostPattern: host,
		TargetType:  targetType,
		Version:     1,    // stale 모드 시 InsertNextVersion 가 자동으로 max+1 로 덮어씀
		Enabled:     true, // CSS selector 검증 통과 = 품질 게이트 — 즉시 활성화하여 pending 재투입이 유효하도록
		Selectors:   selectors,
		Confidence:  confidence,
		Description: fmt.Sprintf("%s (sample url: %s, model: %s)", llmAutoDescription, sampleURL, modelName),
		PageType:    pageType, // EnrichedExtractor 모드에서만 채워짐 — legacy 경로는 "" (미분류, #326).
		Article:     article,  // EnrichedExtractor 의 article 분류 — page rule 만 반영, list 는 항상 false (#423).
	}
	var insertErr error
	if stale {
		// stale 재학습: 기존 v1 보존 + v2 추가.
		insertErr = g.repo.InsertNextVersion(ctx, record)
	} else {
		insertErr = g.repo.Insert(ctx, record)
	}
	if err := insertErr; err != nil {
		// 동일 자연키 (source_name, host_pattern, path_pattern, target_type, version) 룰이 이미
		// DB 에 존재 — 정상 경로로 흡수.
		// 발생 시나리오: 이전 실행이 INSERT 한 룰이 잔존하나 resolver lookup 이 stale 캐시 등으로
		// 룰을 찾지 못해 generate() 진입한 케이스. 또는 사전 lookup 후 race window 에서 다른
		// 인스턴스가 INSERT 완료한 케이스.
		//
		// enabled 여부 / rule_id 를 로그에 포함하여 운영 가시성 ↑.
		// disabled 룰 잔존이면 warn — 운영자가 수동 재활성 결정을 해야 함을 명시.
		if errors.Is(err, storage.ErrDuplicate) {
			// cache invalidate 는 invalidatingRepo decorator 가 ErrDuplicate
			// 시에도 자동 호출 — 본 함수는 순수 로깅 / 분기 책임만.
			fields := map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
			}
			if existing, ferr := g.repo.FindByNaturalKey(ctx, LLMAutoSourceName, host, "", targetType, 1); ferr == nil && existing != nil {
				fields["existing_rule_id"] = existing.ID
				fields["existing_enabled"] = existing.Enabled
				if !existing.Enabled {
					g.log.WithFields(fields).Warn("llmgen Insert ErrDuplicate — existing rule is disabled (manual re-enable required)")
					return nil
				}
			}
			g.log.WithFields(fields).Info("llmgen Insert ErrDuplicate absorbed — rule already exists, cache invalidated")
			return nil
		}
		return fmt.Errorf("insert parsing rule: %w", err)
	}

	// cache invalidate 는 invalidatingRepo decorator 가 자동 호출.

	g.log.WithFields(map[string]interface{}{
		"host":        host,
		"target_type": string(targetType),
		"rule_id":     record.ID,
		"model":       modelName,
		"enabled":     true,
	}).Info("llm-generated parsing rule inserted and enabled")

	return nil
}

// parseSelectorMap 은 LLM 응답 텍스트에서 SelectorMap JSON 을 추출 + decode 합니다.
func parseSelectorMap(content string) (model.SelectorMap, error) {
	jsonStr := extractJSON(content)
	if jsonStr == "" {
		return model.SelectorMap{}, errors.New("no JSON object found in response")
	}
	var sm model.SelectorMap
	if err := json.Unmarshal([]byte(jsonStr), &sm); err != nil {
		return model.SelectorMap{}, fmt.Errorf("unmarshal selector map: %w", err)
	}
	return sm, nil
}

// validateSelectors 는 생성된 selector 가 실제 HTML 에 매칭되는지 확인합니다.
//
// target_type 별 핵심 필드가 0건 매칭이면 selector 는 hallucination 으로 간주, ErrInvalid 반환.
//
//   - TargetTypePage: Title + MainContent 둘 다 1건 이상 매칭
//   - TargetTypeList: ItemContainer + ItemLink 둘 다 1건 이상 매칭 (LinkDiscovery 모드는 미적용)
func validateSelectors(sm model.SelectorMap, targetType model.TargetType, html string) error {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		return fmt.Errorf("goquery parse html: %w", err)
	}

	switch targetType {
	case model.TargetTypeList:
		if !selectorMatches(doc, sm.ItemContainer) {
			return errors.New("ItemContainer selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.ItemLink) {
			return errors.New("ItemLink selector matched 0 elements")
		}
	default: // TargetTypePage and unknown
		if !selectorMatches(doc, sm.Title) {
			return errors.New("Title selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.MainContent) {
			return errors.New("MainContent selector matched 0 elements")
		}
	}
	return nil
}

// selectorMatches 는 selector 가 nil/empty 가 아니고 1건 이상 매칭하는지 확인합니다.
func selectorMatches(doc *goquery.Document, fs *model.FieldSelector) bool {
	if fs == nil || strings.TrimSpace(fs.CSS) == "" {
		return false
	}
	return doc.Find(fs.CSS).Length() > 0
}

// handleBlacklistDecision 은 EnrichedExtractor 가 페이지를 blacklist 로 판정했을 때 호출됩니다.
//
// blacklistSvc (BlacklistService) 가 비-nil 이면 service 에 위임 — path_pattern 변환 / INSERT /
// ErrDuplicate 흡수 / 로그 모두 service 책임. 본 메서드는 nil 분기 + 위임만 (이슈 #431).
func (g *Generator) handleBlacklistDecision(ctx context.Context, host, sampleURL string, targetType model.TargetType, decision *BlacklistDecision) {
	if g.blacklistSvc == nil {
		g.log.WithFields(map[string]interface{}{
			"host":             host,
			"sample_url":       sampleURL,
			"target_type":      string(targetType),
			"blacklist_reason": decision.Reason,
		}).Info("page judged as blacklist by LLM but blacklistSvc not wired — selector insert skipped only")
		return
	}
	// service 가 INSERT / ErrDuplicate / 로그 모두 처리 — Generator 는 결과 무시 (모든 실패 non-fatal).
	_, _ = g.blacklistSvc.HandleLLMDecision(ctx, host, sampleURL, targetType, decision.Reason)
}

// pathPatternFromURL 은 service/blacklist.go 로 이전 (이슈 #431).
