// Package llmgen 은 LLM 으로 parsing rule 을 자동 생성하는 컴포넌트입니다 (이슈 #149).
//
// Package llmgen automatically generates parsing_rules entries via LLM when a host
// has no rule registered (rule.ErrNoRule fallback path).
//
// 흐름:
//  1. parser_worker 가 rule.ErrNoRule 발견 → Generator.Enqueue 호출 (비동기 / 즉시 반환)
//  2. Generator goroutine: in-flight dedup 후 LLM 프롬프트 생성 → Provider.Generate 호출
//  3. 응답 JSON 파싱 → storage.SelectorMap 으로 변환
//  4. validation: 생성된 selector 로 실제 HTML 매칭 확인 (0건이면 폐기)
//  5. ParsingRuleRepository.Insert (enabled=false — 운영자 review 후 enabled=true flip)
//  6. Resolver.Invalidate 로 negative cache flush — 다음 fetch 부터 새 rule 사용 가능
//
// 본 PR scope (이슈 #149 1차):
//   - 단일 LLM 호출 + 기본 validation + DB INSERT + cache invalidate
//   - Best-effort in-process dedup (단일 instance 보호)
//   - enabled=false 로 INSERT (운영자 spot-check 게이트)
//
// 후속 PR scope (이슈 TBD 2차):
//   - 비용 cap (일일 / 시간당 호출 수 제한)
//   - audit log + Prometheus metric
//   - 분산 dedup (Redis lock)
package llmgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/PuerkitoBio/goquery"

	"issuetracker/internal/processor/fetcher/core"
	"issuetracker/internal/processor/parser/rule"
	"issuetracker/internal/storage"
	"issuetracker/pkg/llm"
	"issuetracker/pkg/logger"
)

// LLMAutoSourceName 은 LLM 으로 자동 생성된 rule row 의 source_name 값입니다.
// 운영 대시보드 / 운영자 review 시 hand-tuned rule 과 구분 가능 (이슈 #149).
//
// 외부 패키지 (예: parser_worker 의 sample 누적 — 이슈 #173 단계 4-1) 도 본 상수를 사용 —
// 동기화 누락 방지 (PR #189 gemini 피드백).
const LLMAutoSourceName = "llm-auto"

// llmAutoDescription 은 자동 생성 row 의 description prefix 입니다.
const llmAutoDescription = "auto-generated by llmgen — review before enabling"

// selectorValidationError 는 validateSelectors 실패를 나타내는 sentinel 타입입니다.
// Enqueue goroutine 에서 다른 에러 (LLM API 실패, JSON 파싱 실패 등) 와 구분하여
// validate 실패일 때만 validateFailureHandler 를 호출하기 위해 사용합니다 (이슈 #237).
type selectorValidationError struct{ cause error }

func (e *selectorValidationError) Error() string {
	return "validate generated selectors: " + e.cause.Error()
}
func (e *selectorValidationError) Unwrap() error { return e.cause }

// SelectorExtractor 는 HTML 에서 CSS 셀렉터를 추출하는 인터페이스입니다 (이슈 #256).
//
// 기본 구현: pkg/llm.Provider 기반 LLM 호출 (Gemini Flash 등).
// 대체 구현: claudegen.Executor (Claude Code Docker).
// SetExtractor 로 교체하면 추출 단계만 대체되고 나머지 흐름 (validation, INSERT) 은 동일.
type SelectorExtractor interface {
	Extract(ctx context.Context, host string, targetType storage.TargetType, html string) (storage.SelectorMap, error)
}

// Generator 는 host 별 parsing rule 을 LLM 으로 자동 생성합니다.
//
// goroutine-safe — provider / repo / resolver 가 자체 thread-safety 를 가짐.
// inflightSet 은 자체 mutex 로 보호.
//
// Lifecycle:
//   - Enqueue 가 background goroutine 으로 LLM 호출 수행 — sync.WaitGroup 으로 추적
//   - Stop(ctx) 호출 시 새 Enqueue 차단 + 진행 중 goroutine 의 완료 대기 (graceful shutdown)
//   - Stop 후 Enqueue 는 noop (race 안전)
type Generator struct {
	provider  llm.Provider
	extractor SelectorExtractor // nil 이면 provider 로 fallback (이슈 #256)
	repo      storage.ParsingRuleRepository
	resolver  *rule.Resolver
	log       *logger.Logger

	// validateFailureHandler 는 selector 검증 실패 시 호출되는 콜백입니다 (이슈 #237).
	// 인자: (ctx, ref, llmRetryCount, targetType, crawlerName).
	//   - ref: raw *core.RawContent 의 경량 snapshot — goroutine 내 포인터 공유 없이 값 전달 (Copilot 피드백).
	//   - targetType, crawlerName: Kafka 메시지 헤더 복원에 필요 (gemini/Copilot/CodeRabbit 피드백).
	// background goroutine 에서 호출 — thread-safe 책임은 핸들러에 있음.
	// nil 이면 호출 안 함.
	validateFailureHandler func(context.Context, core.RawContentRef, int, storage.TargetType, string)

	inflight *inflightSet
	wg       sync.WaitGroup
	stopped  atomic.Bool
}

// SetValidateFailureHandler 는 selector 검증 실패 시 호출할 콜백을 등록합니다 (이슈 #237).
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetValidateFailureHandler(fn func(context.Context, core.RawContentRef, int, storage.TargetType, string)) {
	g.validateFailureHandler = fn
}

// SetExtractor 는 셀렉터 추출 단계를 교체합니다 (이슈 #256).
// nil 이면 기존 provider (Gemini Flash 등) 로 fallback.
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetExtractor(e SelectorExtractor) {
	g.extractor = e
}

// New 는 Generator 를 생성합니다.
//
// provider / repo / resolver / log 모두 비-nil 필수. 하나라도 nil 이면 error —
// 호출자 (cmd/main) 가 boot fatal 처리 (이슈 #208).
func New(provider llm.Provider, repo storage.ParsingRuleRepository, resolver *rule.Resolver, log *logger.Logger) (*Generator, error) {
	if provider == nil {
		return nil, errors.New("llmgen: New requires non-nil provider")
	}
	if repo == nil {
		return nil, errors.New("llmgen: New requires non-nil repo")
	}
	if resolver == nil {
		return nil, errors.New("llmgen: New requires non-nil resolver")
	}
	if log == nil {
		return nil, errors.New("llmgen: New requires non-nil log")
	}
	return &Generator{
		provider: provider,
		repo:     repo,
		resolver: resolver,
		log:      log,
		inflight: newInflightSet(),
	}, nil
}

// Enqueue 는 (host, type) 에 대한 LLM rule 생성을 비동기로 시작합니다.
//
// Enqueue starts an async generation attempt and returns immediately. raw 의 HTML 을
// LLM 프롬프트 입력으로 사용 — 호출자가 Enqueue 후 raw 를 폐기해도 안전하도록 필요 데이터를 캡쳐.
//
// llmRetryCount 는 호출자 (parser_worker) 가 RawContentRef 에서 전달하는 재큐 횟수입니다.
// crawlerName 은 Kafka 메시지 헤더 복원용 — validateSelectors 실패 시 재큐 메시지에 포함됩니다.
// validateSelectors 실패 시 validateFailureHandler 가 등록되어 있으면
// (ctx, ref, llmRetryCount, targetType, crawlerName) 으로 호출됩니다 (이슈 #237).
//
// 동일 (host, type) 에 대한 in-flight 호출이 이미 있으면 즉시 skip.
// Stop 호출 후의 Enqueue 는 즉시 noop.
func (g *Generator) Enqueue(ctx context.Context, host string, targetType storage.TargetType, raw *core.RawContent, llmRetryCount int, crawlerName string) {
	if g.stopped.Load() {
		return
	}
	if raw == nil || raw.HTML == "" {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).Debug("llmgen enqueue skipped — empty raw")
		return
	}

	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return
	}

	// 필요한 데이터를 값으로 캡쳐 — goroutine 내 포인터 공유 없이 안전 (Copilot 피드백).
	htmlSnapshot := raw.HTML
	urlSnapshot := raw.URL
	rawRef := core.RawContentRef{
		ID:         raw.ID,
		URL:        raw.URL,
		FetchedAt:  raw.FetchedAt,
		SourceInfo: raw.SourceInfo,
	}

	if !g.inflight.tryAcquire(host, targetType) {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).Debug("llmgen enqueue skipped — in-flight request already exists")
		return
	}

	// 호출자 ctx 의 cancel 은 무시 (best-effort 후속 작업) — trace ID 등 메타데이터 보존.
	bgCtx := context.WithoutCancel(ctx)

	g.wg.Add(1)
	go func() {
		defer g.wg.Done()
		defer g.inflight.release(host, targetType)

		err := g.runOnce(bgCtx, host, targetType, urlSnapshot, htmlSnapshot)
		if err != nil {
			logger.FromContext(bgCtx).WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
				"url":         urlSnapshot,
			}).WithError(err).Warn("llmgen rule generation failed")

			// selector 검증 실패인 경우에만 재큐 콜백 호출 (이슈 #237).
			// rawRef (값 복사) + targetType + crawlerName 전달 — 헤더 복원에 사용.
			var sve *selectorValidationError
			if errors.As(err, &sve) && g.validateFailureHandler != nil {
				g.validateFailureHandler(bgCtx, rawRef, llmRetryCount, targetType, crawlerName)
			}
		}
	}()
}

// Stop 은 새 Enqueue 를 차단하고 진행 중인 background goroutine 의 완료를 대기합니다 (graceful shutdown).
//
// ctx 가 cancel 되면 in-flight 호출 완료 대기를 중단하고 즉시 반환 — 단, 진행 중 goroutine
// 자체는 background ctx (WithoutCancel) 로 동작하므로 Stop 반환 후에도 LLM 호출은 계속 진행될 수 있음.
// 운영자가 진정한 hard stop 을 원하면 process kill 필요 (LLM 호출 자체 timeout 은 LLMConfig.Timeout 으로 제어).
//
// 호출자가 Stop 을 호출하기 전에 새 Enqueue source (parser worker) 가 먼저 정지되어야 함 —
// 그래야 Stop 이 반환된 시점에 모든 in-flight 호출이 정리되었음을 보장할 수 있음.
//
// Idempotent — 여러 번 호출되어도 안전 (두 번째 호출은 즉시 반환).
func (g *Generator) Stop(ctx context.Context) {
	if !g.stopped.CompareAndSwap(false, true) {
		return // 이미 Stop 호출됨
	}

	done := make(chan struct{})
	go func() {
		g.wg.Wait()
		close(done)
	}()

	select {
	case <-done:
		g.log.Info("llmgen generator stopped — all in-flight requests completed")
	case <-ctx.Done():
		g.log.Warn("llmgen generator stop timeout — in-flight LLM calls may still be running in background")
	}
}

// runOnce 는 단일 추출 + validation + INSERT + cache invalidate 의 동기 실행입니다.
// 호출자 (Enqueue 의 goroutine) 가 in-flight 슬롯 release 책임.
func (g *Generator) runOnce(ctx context.Context, host string, targetType storage.TargetType, sampleURL, html string) error {
	var (
		selectors storage.SelectorMap
		modelName string
	)

	if g.extractor != nil {
		// Claude Code Docker 추출 경로 (이슈 #256)
		sm, err := g.extractor.Extract(ctx, host, targetType, html)
		if err != nil {
			return fmt.Errorf("claude code extractor: %w", err)
		}
		selectors = sm
		modelName = "claude-code"
	} else {
		// 기존 LLM provider 경로 (Gemini Flash 등)
		system, user := BuildPrompt(host, targetType, html)
		resp, err := g.provider.Generate(ctx, llm.Request{
			Messages: []llm.Message{
				{Role: llm.RoleSystem, Content: system},
				{Role: llm.RoleUser, Content: user},
			},
			TaskHint: llm.TaskHintJSON,
		})
		if err != nil {
			return fmt.Errorf("llm provider call: %w", err)
		}
		if resp == nil || resp.Content == "" {
			return errors.New("llm returned empty response")
		}
		sm, err := parseSelectorMap(resp.Content)
		if err != nil {
			return fmt.Errorf("parse llm response: %w", err)
		}
		selectors = sm
		modelName = resp.Model
	}

	if err := validateSelectors(selectors, targetType, html); err != nil {
		return &selectorValidationError{cause: err}
	}

	record := &storage.ParsingRuleRecord{
		SourceName:  LLMAutoSourceName,
		HostPattern: host,
		TargetType:  targetType,
		Version:     1,
		Enabled:     false, // 운영자 review 게이트 — spot-check 후 수동 enable
		Selectors:   selectors,
		Description: fmt.Sprintf("%s (sample url: %s, model: %s)", llmAutoDescription, sampleURL, modelName),
	}
	if err := g.repo.Insert(ctx, record); err != nil {
		return fmt.Errorf("insert parsing rule: %w", err)
	}

	// negative cache 만 즉시 무효화 — enabled=false 상태이므로 다음 lookup 도 ErrNoRule 이지만,
	// 운영자가 enabled=true 로 flip 한 직후 새 rule 이 즉시 반영되도록 cache 비움.
	g.resolver.Invalidate(host, targetType)

	g.log.WithFields(map[string]interface{}{
		"host":        host,
		"target_type": string(targetType),
		"rule_id":     record.ID,
		"model":       modelName,
		"enabled":     false,
	}).Info("llm-generated parsing rule inserted (review required before enabling)")

	return nil
}

// parseSelectorMap 은 LLM 응답 텍스트에서 SelectorMap JSON 을 추출 + decode 합니다.
func parseSelectorMap(content string) (storage.SelectorMap, error) {
	jsonStr := extractJSON(content)
	if jsonStr == "" {
		return storage.SelectorMap{}, errors.New("no JSON object found in response")
	}
	var sm storage.SelectorMap
	if err := json.Unmarshal([]byte(jsonStr), &sm); err != nil {
		return storage.SelectorMap{}, fmt.Errorf("unmarshal selector map: %w", err)
	}
	return sm, nil
}

// validateSelectors 는 생성된 selector 가 실제 HTML 에 매칭되는지 확인합니다.
//
// target_type 별 핵심 필드가 0건 매칭이면 selector 는 hallucination 으로 간주, ErrInvalid 반환.
//
//   - TargetTypePage: Title + MainContent 둘 다 1건 이상 매칭
//   - TargetTypeList: ItemContainer + ItemLink 둘 다 1건 이상 매칭 (LinkDiscovery 모드는 본 PR scope 외)
func validateSelectors(sm storage.SelectorMap, targetType storage.TargetType, html string) error {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		return fmt.Errorf("goquery parse html: %w", err)
	}

	switch targetType {
	case storage.TargetTypeList:
		if !selectorMatches(doc, sm.ItemContainer) {
			return errors.New("ItemContainer selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.ItemLink) {
			return errors.New("ItemLink selector matched 0 elements")
		}
	default: // TargetTypePage and unknown
		if !selectorMatches(doc, sm.Title) {
			return errors.New("Title selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.MainContent) {
			return errors.New("MainContent selector matched 0 elements")
		}
	}
	return nil
}

// selectorMatches 는 selector 가 nil/empty 가 아니고 1건 이상 매칭하는지 확인합니다.
func selectorMatches(doc *goquery.Document, fs *storage.FieldSelector) bool {
	if fs == nil || strings.TrimSpace(fs.CSS) == "" {
		return false
	}
	return doc.Find(fs.CSS).Length() > 0
}
