// Package llmgen 은 LLM 으로 parsing rule 을 자동 생성하는 컴포넌트입니다 (이슈 #149).
//
// Package llmgen automatically generates parsing_rules entries via LLM when a host
// has no rule registered (rule.ErrNoRule fallback path).
//
// 흐름:
//  1. parser_worker 가 rule.ErrNoRule 발견 → Generator.Enqueue 호출 (비동기 / 즉시 반환)
//  2. Generator goroutine: in-flight dedup 후 LLM 프롬프트 생성 → Provider.Generate 호출
//  3. 응답 JSON 파싱 → storage.SelectorMap 으로 변환
//  4. validation: 생성된 selector 로 실제 HTML 매칭 확인 (0건이면 폐기)
//  5. ParsingRuleRepository.Insert (enabled=true — CSS selector 검증 통과가 품질 게이트)
//  6. Resolver.Invalidate 로 negative cache flush — 다음 fetch 부터 새 rule 사용 가능
//
// 본 PR scope (이슈 #149 1차):
//   - 단일 LLM 호출 + 기본 validation + DB INSERT + cache invalidate
//   - Best-effort in-process dedup (단일 instance 보호)
//
// 후속 PR scope (이슈 TBD 2차):
//   - 비용 cap (일일 / 시간당 호출 수 제한)
//   - audit log + Prometheus metric
//   - 분산 dedup (Redis lock)
package llmgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/PuerkitoBio/goquery"

	"issuetracker/internal/processor/fetcher/core"
	"issuetracker/internal/processor/parser/rule"
	"issuetracker/internal/storage"
	"issuetracker/pkg/llm"
	"issuetracker/pkg/logger"
)

// LLMAutoSourceName 은 LLM 으로 자동 생성된 rule row 의 source_name 값입니다.
// 운영 대시보드 / 운영자 review 시 hand-tuned rule 과 구분 가능 (이슈 #149).
//
// 외부 패키지 (예: parser_worker 의 sample 누적 — 이슈 #173 단계 4-1) 도 본 상수를 사용 —
// 동기화 누락 방지 (PR #189 gemini 피드백).
const LLMAutoSourceName = "llm-auto"

// llmAutoDescription 은 자동 생성 row 의 description prefix 입니다.
const llmAutoDescription = "auto-generated by llmgen — review before enabling"

// SelectorValidator 는 생성된 셀렉터의 의미 검증 인터페이스입니다 (이슈 #257).
// DOM 매칭 검증 이후 추가 단계로 실행 — 추출 내용이 실제 뉴스 제목/본문인지 LLM 으로 확인.
// nil 이면 의미 검증 건너뜀 (DOM 검증만 수행).
type SelectorValidator interface {
	Validate(ctx context.Context, html string, selectors storage.SelectorMap, targetType storage.TargetType) (SelectorValidatorResult, error)
}

// SelectorValidatorResult 는 의미 검증 결과입니다.
type SelectorValidatorResult struct {
	Valid  bool
	Reason string
}

// SelectorExtractor 는 HTML 에서 CSS 셀렉터를 추출하는 인터페이스입니다 (이슈 #256).
//
// 기본 구현: pkg/llm.Provider 기반 LLM 호출 (Gemini Flash 등).
// 대체 구현: claudegen.ClaudeWorker (Claude Code 웜 컨테이너).
// SetExtractor 로 교체하면 추출 단계만 대체되고 나머지 흐름 (validation, INSERT) 은 동일.
type SelectorExtractor interface {
	Extract(ctx context.Context, host string, targetType storage.TargetType, html string) (storage.SelectorMap, error)
}

// modelNamer 는 추출기가 사용하는 모델 ID 를 반환하는 선택적 인터페이스입니다 (이슈 #256).
// SelectorExtractor 구현체가 이 인터페이스도 구현하면 실제 모델 ID 를 DB description 에 기록합니다.
// 구현하지 않으면 fallback "claude-code" 를 사용합니다.
type modelNamer interface {
	ModelName() string
}

// selectorValidationError 는 validateSelectors 실패를 나타내는 sentinel 타입입니다.
// Enqueue goroutine 에서 다른 에러 (LLM API 실패, JSON 파싱 실패 등) 와 구분하여
// validate 실패일 때만 validateFailureHandler 를 호출하기 위해 사용합니다 (이슈 #237).
type selectorValidationError struct{ cause error }

func (e *selectorValidationError) Error() string {
	return "validate generated selectors: " + e.cause.Error()
}
func (e *selectorValidationError) Unwrap() error { return e.cause }

// Generator 는 host 별 parsing rule 을 LLM 으로 자동 생성합니다.
//
// goroutine-safe — provider / repo / resolver 가 자체 thread-safety 를 가짐.
// locker 는 InflightLocker 구현체에 따라 자체 thread-safety 를 가짐.
//
// Lifecycle:
//   - Enqueue 가 background goroutine 으로 LLM 호출 수행 — sync.WaitGroup 으로 추적
//   - Stop(ctx) 호출 시 새 Enqueue 차단 + 진행 중 goroutine 의 완료 대기 (graceful shutdown)
//   - Stop 후 Enqueue 는 noop (race 안전)
type Generator struct {
	provider  llm.Provider
	extractor SelectorExtractor // nil 이면 provider 로 fallback (이슈 #256)
	repo      storage.ParsingRuleRepository
	resolver  *rule.Resolver
	log       *logger.Logger

	// validateFailureHandler 는 selector 검증 실패 시 호출되는 콜백입니다 (이슈 #237).
	// 인자: (ctx, ref, llmRetryCount, targetType, crawlerName).
	//   - ref: raw *core.RawContent 의 경량 snapshot — goroutine 내 포인터 공유 없이 값 전달 (Copilot 피드백).
	//   - targetType, crawlerName: Kafka 메시지 헤더 복원에 필요 (gemini/Copilot/CodeRabbit 피드백).
	// background goroutine 에서 호출 — thread-safe 책임은 핸들러에 있음.
	// nil 이면 호출 안 함.
	validateFailureHandler func(context.Context, core.RawContentRef, int, storage.TargetType, string)

	locker       InflightLocker    // 기본: memInflightLocker, Redis 활성 시: RedisInflightLocker (이슈 #261)
	pendingQueue PendingQueue      // nil 이면 pending URL 보존 비활성 (이슈 #262)
	requeueFn    RequeueFunc       // nil 이면 재투입 비활성 (이슈 #262)
	semValidator SelectorValidator // nil 이면 의미 검증 건너뜀 (이슈 #257)
	wg           sync.WaitGroup
	stopped      atomic.Bool
}

// SetValidateFailureHandler 는 selector 검증 실패 시 호출할 콜백을 등록합니다 (이슈 #237).
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetValidateFailureHandler(fn func(context.Context, core.RawContentRef, int, storage.TargetType, string)) {
	g.validateFailureHandler = fn
}

// SetPendingQueue 는 대기 URL 큐와 재투입 콜백을 등록합니다 (이슈 #262).
// 둘 다 비-nil 이어야 활성화됩니다. Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로
// 초기화 시 1회만 호출합니다.
func (g *Generator) SetPendingQueue(pq PendingQueue, fn RequeueFunc) {
	g.pendingQueue = pq
	g.requeueFn = fn
}

// SetLocker 는 분산 Lock 구현체를 교체합니다 (이슈 #261).
// nil 이면 기본 in-process memInflightLocker 로 fallback.
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetLocker(l InflightLocker) {
	if l == nil {
		g.locker = newMemInflightLocker()
		return
	}
	g.locker = l
}

// SetSelectorValidator 는 의미 검증기를 등록합니다 (이슈 #257).
// nil 이면 의미 검증 건너뜀. Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로
// 초기화 시 1회만 호출합니다.
func (g *Generator) SetSelectorValidator(v SelectorValidator) {
	g.semValidator = v
}

// SetExtractor 는 셀렉터 추출 단계를 교체합니다 (이슈 #256).
// nil 이면 기존 provider (Gemini Flash 등) 로 fallback.
// Stop 전에 설정해야 하며, goroutine-safe 하지 않으므로 초기화 시 1회만 호출합니다.
func (g *Generator) SetExtractor(e SelectorExtractor) {
	g.extractor = e
}

// New 는 Generator 를 생성합니다.
//
// provider / repo / resolver / log 모두 비-nil 필수. 하나라도 nil 이면 error —
// 호출자 (cmd/main) 가 boot fatal 처리 (이슈 #208).
func New(provider llm.Provider, repo storage.ParsingRuleRepository, resolver *rule.Resolver, log *logger.Logger) (*Generator, error) {
	if provider == nil {
		return nil, errors.New("llmgen: New requires non-nil provider")
	}
	if repo == nil {
		return nil, errors.New("llmgen: New requires non-nil repo")
	}
	if resolver == nil {
		return nil, errors.New("llmgen: New requires non-nil resolver")
	}
	if log == nil {
		return nil, errors.New("llmgen: New requires non-nil log")
	}
	return &Generator{
		provider: provider,
		repo:     repo,
		resolver: resolver,
		log:      log,
		locker:   newMemInflightLocker(),
	}, nil
}

// Enqueue 는 (host, type) 에 대한 LLM rule 생성을 비동기로 시작합니다.
//
// Enqueue starts an async generation attempt and returns immediately. raw 의 HTML 을
// LLM 프롬프트 입력으로 사용 — 호출자가 Enqueue 후 raw 를 폐기해도 안전하도록 필요 데이터를 캡쳐.
//
// llmRetryCount 는 호출자 (parser_worker) 가 RawContentRef 에서 전달하는 재큐 횟수입니다.
// crawlerName 은 Kafka 메시지 헤더 복원용 — validateSelectors 실패 시 재큐 메시지에 포함됩니다.
// jobTimeout 은 원본 crawl job 의 timeout — pending 재투입 시 카테고리 chained job timeout 보존 (이슈 #262 리뷰).
// validateSelectors 실패 시 validateFailureHandler 가 등록되어 있으면
// (ctx, ref, llmRetryCount, targetType, crawlerName) 으로 호출됩니다 (이슈 #237).
//
// 동일 (host, type) 에 대한 in-flight 호출이 이미 있으면 즉시 skip.
// Stop 호출 후의 Enqueue 는 즉시 noop.
func (g *Generator) Enqueue(ctx context.Context, host string, targetType storage.TargetType, raw *core.RawContent, llmRetryCount int, crawlerName string, jobTimeout time.Duration) {
	if g.stopped.Load() {
		return
	}
	if raw == nil || raw.HTML == "" {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).Debug("llmgen enqueue skipped — empty raw")
		return
	}

	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return
	}

	// 필요한 데이터를 값으로 캡쳐 — goroutine 내 포인터 공유 없이 안전 (Copilot 피드백).
	htmlSnapshot := raw.HTML
	urlSnapshot := raw.URL
	rawRef := core.RawContentRef{
		ID:         raw.ID,
		URL:        raw.URL,
		FetchedAt:  raw.FetchedAt,
		SourceInfo: raw.SourceInfo,
	}

	// TryAcquire: WithoutCancel 후 timeout — 호출자 ctx cancel 이 즉시 전파되지 않도록 하되
	// Redis 장애 시 무기한 블록도 방지. 기존 inflightSet 동작(cancel 무시)과 일관성 유지.
	acquireCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 5*time.Second)
	acquired, err := g.locker.TryAcquire(acquireCtx, host, targetType)
	cancel()
	if err != nil {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).WithError(err).Warn("llmgen inflight lock acquire failed, skipping")
		return
	}
	if !acquired {
		// in-flight 중 — pending 큐에 적재하여 룰 생성 완료 후 재파싱 (이슈 #262).
		if g.pendingQueue != nil {
			item := PendingItem{
				RawRef:        rawRef,
				CrawlerName:   crawlerName,
				LLMRetryCount: llmRetryCount,
				TargetType:    targetType,
				TimeoutMs:     jobTimeout.Milliseconds(),
			}
			if perr := g.pendingQueue.Push(context.WithoutCancel(ctx), host, targetType, item); perr != nil {
				g.log.WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
				}).WithError(perr).Warn("llmgen pending queue push failed")
			} else {
				g.log.WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
					"url":         rawRef.URL,
				}).Debug("llmgen enqueue deferred — added to pending queue")
			}
		} else {
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
			}).Debug("llmgen enqueue skipped — in-flight request already exists")
		}
		return
	}

	// 호출자 ctx 의 cancel 은 무시 (best-effort 후속 작업) — trace ID 등 메타데이터 보존.
	bgCtx := context.WithoutCancel(ctx)

	g.wg.Add(1)
	go func() {
		defer g.wg.Done()
		defer func() {
			if rerr := g.locker.Release(bgCtx, host, targetType); rerr != nil {
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
				}).WithError(rerr).Warn("llmgen inflight lock release failed")
			}
		}()

		err := g.runOnce(bgCtx, host, targetType, urlSnapshot, htmlSnapshot)
		if err != nil {
			logger.FromContext(bgCtx).WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
				"url":         urlSnapshot,
			}).WithError(err).Warn("llmgen rule generation failed")

			// selector 검증 실패인 경우에만 재큐 콜백 호출 (이슈 #237).
			// rawRef (값 복사) + targetType + crawlerName 전달 — 헤더 복원에 사용.
			var sve *selectorValidationError
			if errors.As(err, &sve) && g.validateFailureHandler != nil {
				g.validateFailureHandler(bgCtx, rawRef, llmRetryCount, targetType, crawlerName)
			}
			return
		}

		// 룰 생성 성공 — pending 대기 URL 을 파서 워커에 재투입 (이슈 #262).
		// flush 는 defer(Release) 실행 전에 수행됨 — flush 중 새로 들어온 URL 은 pending 에 적재되고
		// 락 해제 후 새 runOnce 가 다음 flush 에서 처리.
		// Kafka publish 실패 항목은 requeueFn 이 반환 → pending 에 재적재 (이슈 #262 리뷰).
		if g.pendingQueue != nil && g.requeueFn != nil {
			items, ferr := g.pendingQueue.Flush(bgCtx, host, targetType)
			if ferr != nil {
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
				}).WithError(ferr).Warn("llmgen pending queue flush failed")
			} else if len(items) > 0 {
				failed := g.requeueFn(bgCtx, items)
				for _, item := range failed {
					if perr := g.pendingQueue.Push(bgCtx, host, targetType, item); perr != nil {
						logger.FromContext(bgCtx).WithFields(map[string]interface{}{
							"host":        host,
							"target_type": string(targetType),
							"url":         item.RawRef.URL,
						}).WithError(perr).Warn("llmgen failed to re-push Kafka-failed pending item")
					}
				}
				logger.FromContext(bgCtx).WithFields(map[string]interface{}{
					"host":        host,
					"target_type": string(targetType),
					"count":       len(items),
					"failed":      len(failed),
				}).Info("llmgen pending URLs requeued for parsing")
			}
		}
	}()
}

// Stop 은 새 Enqueue 를 차단하고 진행 중인 background goroutine 의 완료를 대기합니다 (graceful shutdown).
//
// ctx 가 cancel 되면 in-flight 호출 완료 대기를 중단하고 즉시 반환 — 단, 진행 중 goroutine
// 자체는 background ctx (WithoutCancel) 로 동작하므로 Stop 반환 후에도 LLM 호출은 계속 진행될 수 있음.
// 운영자가 진정한 hard stop 을 원하면 process kill 필요 (LLM 호출 자체 timeout 은 LLMConfig.Timeout 으로 제어).
//
// 호출자가 Stop 을 호출하기 전에 새 Enqueue source (parser worker) 가 먼저 정지되어야 함 —
// 그래야 Stop 이 반환된 시점에 모든 in-flight 호출이 정리되었음을 보장할 수 있음.
//
// Idempotent — 여러 번 호출되어도 안전 (두 번째 호출은 즉시 반환).
func (g *Generator) Stop(ctx context.Context) {
	if !g.stopped.CompareAndSwap(false, true) {
		return // 이미 Stop 호출됨
	}

	done := make(chan struct{})
	go func() {
		g.wg.Wait()
		close(done)
	}()

	select {
	case <-done:
		g.log.Info("llmgen generator stopped — all in-flight requests completed")
	case <-ctx.Done():
		g.log.Warn("llmgen generator stop timeout — in-flight LLM calls may still be running in background")
	}
}

// runOnce 는 단일 추출 + validation + INSERT + cache invalidate 의 동기 실행입니다.
// 호출자 (Enqueue 의 goroutine) 가 in-flight 슬롯 release 책임.
func (g *Generator) runOnce(ctx context.Context, host string, targetType storage.TargetType, sampleURL, html string) error {
	// 사전 lookup (이슈 #274) — 동일 자연키 룰이 이미 DB 에 존재하면 LLM 호출 회피.
	// resolver lookup 이 stale 캐시 / disabled 룰 등으로 못 찾는 케이스를 LLM 호출 (~55s sonnet)
	// 으로 가지 않게 차단. lookup 실패는 best-effort — 에러는 무시하고 LLM 경로로 진행.
	if existing, err := g.repo.FindByNaturalKey(ctx, LLMAutoSourceName, host, "", targetType, 1); err == nil && existing != nil {
		g.resolver.Invalidate(host, targetType)
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
			"rule_id":     existing.ID,
			"enabled":     existing.Enabled,
		}).Info("llmgen pre-check hit — rule already exists, skipping LLM call")
		return nil
	}

	var (
		selectors storage.SelectorMap
		modelName string
	)

	if g.extractor != nil {
		// Claude Code 웜 컨테이너 추출 경로 (이슈 #256)
		sm, err := g.extractor.Extract(ctx, host, targetType, html)
		if err != nil {
			return fmt.Errorf("claude code extractor: %w", err)
		}
		selectors = sm
		// 추출기가 ModelName() 을 구현하면 실제 모델 ID 를 사용, 없으면 fallback.
		if mn, ok := g.extractor.(modelNamer); ok {
			modelName = mn.ModelName()
		} else {
			modelName = "claude-code"
		}
	} else {
		// 기존 LLM provider 경로 (Gemini Flash 등)
		system, user := BuildPrompt(host, targetType, html)
		resp, err := g.provider.Generate(ctx, llm.Request{
			Messages: []llm.Message{
				{Role: llm.RoleSystem, Content: system},
				{Role: llm.RoleUser, Content: user},
			},
			TaskHint: llm.TaskHintJSON,
		})
		if err != nil {
			return fmt.Errorf("llm provider call: %w", err)
		}
		if resp == nil || resp.Content == "" {
			return errors.New("llm returned empty response")
		}
		sm, err := parseSelectorMap(resp.Content)
		if err != nil {
			return fmt.Errorf("parse llm response: %w", err)
		}
		selectors = sm
		modelName = resp.Model
	}

	if err := validateSelectors(selectors, targetType, html); err != nil {
		return &selectorValidationError{cause: err}
	}

	// 의미 검증 — DOM 매칭 후 추출 내용이 실제로 뉴스 제목/본문인지 LLM 으로 확인 (이슈 #257).
	if g.semValidator != nil {
		res, verr := g.semValidator.Validate(ctx, html, selectors, targetType)
		if verr != nil {
			// API 오류 — best-effort: 검증 인프라 장애가 rule 생성을 막지 않도록 warn 로그만 남기고 계속.
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
			}).WithError(verr).Warn("semantic validator API error, proceeding without semantic validation")
		} else if !res.Valid {
			return &selectorValidationError{cause: fmt.Errorf("semantic validation failed: %s", res.Reason)}
		}
	}

	record := &storage.ParsingRuleRecord{
		SourceName:  LLMAutoSourceName,
		HostPattern: host,
		TargetType:  targetType,
		Version:     1,
		Enabled:     true, // CSS selector 검증 통과 = 품질 게이트 — 즉시 활성화하여 pending 재투입이 유효하도록
		Selectors:   selectors,
		Description: fmt.Sprintf("%s (sample url: %s, model: %s)", llmAutoDescription, sampleURL, modelName),
	}
	if err := g.repo.Insert(ctx, record); err != nil {
		// 동일 자연키 (source_name, host_pattern, path_pattern, target_type, version) 룰이 이미
		// DB 에 존재 — 우리가 원하던 최종 상태와 동일하므로 정상 경로로 흡수 (이슈 #274).
		// 발생 시나리오: 이전 실행이 INSERT 한 룰이 잔존하나 resolver lookup 이 stale 캐시 등으로
		// 룰을 찾지 못해 generate() 진입한 케이스.
		if errors.Is(err, storage.ErrDuplicate) {
			g.resolver.Invalidate(host, targetType)
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
			}).Info("llmgen rule already exists in DB, invalidating cache and continuing")
			return nil
		}
		return fmt.Errorf("insert parsing rule: %w", err)
	}

	// negative cache 무효화 — 다음 lookup 부터 새 rule 이 즉시 반영되도록.
	g.resolver.Invalidate(host, targetType)

	g.log.WithFields(map[string]interface{}{
		"host":        host,
		"target_type": string(targetType),
		"rule_id":     record.ID,
		"model":       modelName,
		"enabled":     true,
	}).Info("llm-generated parsing rule inserted and enabled")

	return nil
}

// parseSelectorMap 은 LLM 응답 텍스트에서 SelectorMap JSON 을 추출 + decode 합니다.
func parseSelectorMap(content string) (storage.SelectorMap, error) {
	jsonStr := extractJSON(content)
	if jsonStr == "" {
		return storage.SelectorMap{}, errors.New("no JSON object found in response")
	}
	var sm storage.SelectorMap
	if err := json.Unmarshal([]byte(jsonStr), &sm); err != nil {
		return storage.SelectorMap{}, fmt.Errorf("unmarshal selector map: %w", err)
	}
	return sm, nil
}

// validateSelectors 는 생성된 selector 가 실제 HTML 에 매칭되는지 확인합니다.
//
// target_type 별 핵심 필드가 0건 매칭이면 selector 는 hallucination 으로 간주, ErrInvalid 반환.
//
//   - TargetTypePage: Title + MainContent 둘 다 1건 이상 매칭
//   - TargetTypeList: ItemContainer + ItemLink 둘 다 1건 이상 매칭 (LinkDiscovery 모드는 본 PR scope 외)
func validateSelectors(sm storage.SelectorMap, targetType storage.TargetType, html string) error {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		return fmt.Errorf("goquery parse html: %w", err)
	}

	switch targetType {
	case storage.TargetTypeList:
		if !selectorMatches(doc, sm.ItemContainer) {
			return errors.New("ItemContainer selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.ItemLink) {
			return errors.New("ItemLink selector matched 0 elements")
		}
	default: // TargetTypePage and unknown
		if !selectorMatches(doc, sm.Title) {
			return errors.New("Title selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.MainContent) {
			return errors.New("MainContent selector matched 0 elements")
		}
	}
	return nil
}

// selectorMatches 는 selector 가 nil/empty 가 아니고 1건 이상 매칭하는지 확인합니다.
func selectorMatches(doc *goquery.Document, fs *storage.FieldSelector) bool {
	if fs == nil || strings.TrimSpace(fs.CSS) == "" {
		return false
	}
	return doc.Find(fs.CSS).Length() > 0
}
