// Package llmgen 은 LLM 으로 parsing rule 을 자동 생성하는 컴포넌트입니다 (이슈 #149).
//
// Package llmgen automatically generates parsing_rules entries via LLM when a host
// has no rule registered (rule.ErrNoRule fallback path).
//
// 흐름:
//  1. parser_worker 가 rule.ErrNoRule 발견 → Generator.Enqueue 호출 (비동기 / 즉시 반환)
//  2. Generator goroutine: in-flight dedup 후 LLM 프롬프트 생성 → Provider.Generate 호출
//  3. 응답 JSON 파싱 → storage.SelectorMap 으로 변환
//  4. validation: 생성된 selector 로 실제 HTML 매칭 확인 (0건이면 폐기)
//  5. ParsingRuleRepository.Insert (enabled=false — 운영자 review 후 enabled=true flip)
//  6. Resolver.Invalidate 로 negative cache flush — 다음 fetch 부터 새 rule 사용 가능
//
// 본 PR scope (이슈 #149 1차):
//   - 단일 LLM 호출 + 기본 validation + DB INSERT + cache invalidate
//   - Best-effort in-process dedup (단일 instance 보호)
//   - enabled=false 로 INSERT (운영자 spot-check 게이트)
//
// 후속 PR scope (이슈 TBD 2차):
//   - 비용 cap (일일 / 시간당 호출 수 제한)
//   - audit log + Prometheus metric
//   - 분산 dedup (Redis lock)
package llmgen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"

	"issuetracker/internal/crawler/core"
	"issuetracker/internal/crawler/parser/rule"
	"issuetracker/internal/storage"
	"issuetracker/pkg/llm"
	"issuetracker/pkg/logger"
)

// llmAutoSourceName 은 LLM 으로 자동 생성된 rule row 의 source_name 값입니다.
// 운영 대시보드 / 운영자 review 시 hand-tuned rule 과 구분 가능 (이슈 #149).
const llmAutoSourceName = "llm-auto"

// llmAutoDescription 은 자동 생성 row 의 description prefix 입니다.
const llmAutoDescription = "auto-generated by llmgen — review before enabling"

// Generator 는 host 별 parsing rule 을 LLM 으로 자동 생성합니다.
//
// goroutine-safe — provider / repo / resolver 가 자체 thread-safety 를 가짐.
// inflightSet 은 자체 mutex 로 보호.
type Generator struct {
	provider llm.Provider
	repo     storage.ParsingRuleRepository
	resolver *rule.Resolver
	log      *logger.Logger

	inflight *inflightSet
}

// New 는 Generator 를 생성합니다.
//
// provider / repo / resolver / log 모두 비-nil 필수. 하나라도 nil 이면 panic — wire 누락 즉시 가시화.
func New(provider llm.Provider, repo storage.ParsingRuleRepository, resolver *rule.Resolver, log *logger.Logger) *Generator {
	if provider == nil {
		panic("llmgen: New requires non-nil provider")
	}
	if repo == nil {
		panic("llmgen: New requires non-nil repo")
	}
	if resolver == nil {
		panic("llmgen: New requires non-nil resolver")
	}
	if log == nil {
		panic("llmgen: New requires non-nil log")
	}
	return &Generator{
		provider: provider,
		repo:     repo,
		resolver: resolver,
		log:      log,
		inflight: newInflightSet(),
	}
}

// Enqueue 는 (host, type) 에 대한 LLM rule 생성을 비동기로 시작합니다.
//
// Enqueue starts an async generation attempt and returns immediately. raw 의 HTML 을
// LLM 프롬프트 입력으로 사용 — 호출자는 raw 를 변경/해제하면 안 됨 (호출자가 Enqueue 후
// raw 를 즉시 폐기해도 안전하도록 본 함수가 필요 데이터를 캡쳐).
//
// 동일 (host, type) 에 대한 in-flight 호출이 이미 있으면 즉시 skip — 새 호출 발생 X.
//
// 본 함수는 절대 block 되지 않으며 에러도 반환하지 않습니다 — 모든 실패는 logger 로 기록.
// 호출 worker 의 hot path 에서 안전하게 호출 가능.
func (g *Generator) Enqueue(ctx context.Context, host string, targetType storage.TargetType, raw *core.RawContent) {
	if raw == nil || raw.HTML == "" {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).Debug("llmgen enqueue skipped — empty raw")
		return
	}

	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return
	}

	// raw.HTML 캡쳐 (호출자가 raw 를 폐기해도 안전)
	htmlSnapshot := raw.HTML
	urlSnapshot := raw.URL

	if !g.inflight.tryAcquire(host, targetType) {
		g.log.WithFields(map[string]interface{}{
			"host":        host,
			"target_type": string(targetType),
		}).Debug("llmgen enqueue skipped — in-flight request already exists")
		return
	}

	go func() {
		defer g.inflight.release(host, targetType)

		// 호출자 ctx 가 cancel 되어도 LLM 호출은 진행 — parser worker 의 message commit 과
		// 무관한 best-effort 후속 작업이므로 background ctx 사용. 단, 호출자 logger context 는
		// 전파해 trace ID 등 보존.
		bgCtx := g.log.ToContext(context.Background())
		if err := g.runOnce(bgCtx, host, targetType, urlSnapshot, htmlSnapshot); err != nil {
			g.log.WithFields(map[string]interface{}{
				"host":        host,
				"target_type": string(targetType),
				"url":         urlSnapshot,
			}).WithError(err).Warn("llmgen rule generation failed")
		}
	}()

	_ = ctx // 향후 분산 dedup 시 호출자 ctx 의 trace ID 활용 예정
}

// runOnce 는 단일 LLM 호출 + validation + INSERT + cache invalidate 의 동기 실행입니다.
// 호출자 (Enqueue 의 goroutine) 가 in-flight 슬롯 release 책임.
func (g *Generator) runOnce(ctx context.Context, host string, targetType storage.TargetType, sampleURL, html string) error {
	system, user := BuildPrompt(host, targetType, html)

	resp, err := g.provider.Generate(ctx, llm.Request{
		Messages: []llm.Message{
			{Role: llm.RoleSystem, Content: system},
			{Role: llm.RoleUser, Content: user},
		},
		TaskHint: llm.TaskHintJSON,
	})
	if err != nil {
		return fmt.Errorf("llm provider call: %w", err)
	}
	if resp == nil || resp.Content == "" {
		return errors.New("llm returned empty response")
	}

	selectors, err := parseSelectorMap(resp.Content)
	if err != nil {
		return fmt.Errorf("parse llm response: %w", err)
	}

	if err := validateSelectors(selectors, targetType, html); err != nil {
		return fmt.Errorf("validate generated selectors: %w", err)
	}

	record := &storage.ParsingRuleRecord{
		SourceName:  llmAutoSourceName,
		HostPattern: host,
		TargetType:  targetType,
		Version:     1,
		Enabled:     false, // 운영자 review 게이트 — spot-check 후 수동 enable
		Selectors:   selectors,
		Description: fmt.Sprintf("%s (sample url: %s, model: %s)", llmAutoDescription, sampleURL, resp.Model),
	}
	if err := g.repo.Insert(ctx, record); err != nil {
		return fmt.Errorf("insert parsing rule: %w", err)
	}

	// negative cache 만 즉시 무효화 — enabled=false 상태이므로 다음 lookup 도 ErrNoRule 이지만,
	// 운영자가 enabled=true 로 flip 한 직후 새 rule 이 즉시 반영되도록 cache 비움.
	g.resolver.Invalidate(host, targetType)

	g.log.WithFields(map[string]interface{}{
		"host":        host,
		"target_type": string(targetType),
		"rule_id":     record.ID,
		"model":       resp.Model,
		"enabled":     false,
	}).Info("llm-generated parsing rule inserted (review required before enabling)")

	return nil
}

// parseSelectorMap 은 LLM 응답 텍스트에서 SelectorMap JSON 을 추출 + decode 합니다.
func parseSelectorMap(content string) (storage.SelectorMap, error) {
	jsonStr := extractJSON(content)
	if jsonStr == "" {
		return storage.SelectorMap{}, errors.New("no JSON object found in response")
	}
	var sm storage.SelectorMap
	if err := json.Unmarshal([]byte(jsonStr), &sm); err != nil {
		return storage.SelectorMap{}, fmt.Errorf("unmarshal selector map: %w", err)
	}
	return sm, nil
}

// validateSelectors 는 생성된 selector 가 실제 HTML 에 매칭되는지 확인합니다.
//
// target_type 별 핵심 필드가 0건 매칭이면 selector 는 hallucination 으로 간주, ErrInvalid 반환.
//
//   - TargetTypePage: Title + MainContent 둘 다 1건 이상 매칭
//   - TargetTypeList: ItemContainer + ItemLink 둘 다 1건 이상 매칭 (LinkDiscovery 모드는 본 PR scope 외)
func validateSelectors(sm storage.SelectorMap, targetType storage.TargetType, html string) error {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		return fmt.Errorf("goquery parse html: %w", err)
	}

	switch targetType {
	case storage.TargetTypeList:
		if !selectorMatches(doc, sm.ItemContainer) {
			return errors.New("ItemContainer selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.ItemLink) {
			return errors.New("ItemLink selector matched 0 elements")
		}
	default: // TargetTypePage and unknown
		if !selectorMatches(doc, sm.Title) {
			return errors.New("Title selector matched 0 elements")
		}
		if !selectorMatches(doc, sm.MainContent) {
			return errors.New("MainContent selector matched 0 elements")
		}
	}
	return nil
}

// selectorMatches 는 selector 가 nil/empty 가 아니고 1건 이상 매칭하는지 확인합니다.
func selectorMatches(doc *goquery.Document, fs *storage.FieldSelector) bool {
	if fs == nil || strings.TrimSpace(fs.CSS) == "" {
		return false
	}
	return doc.Find(fs.CSS).Length() > 0
}
