// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/classifier/classifier.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 카테고리 식별자
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // LLM 프롬프트에 포함될 설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInput) Reset() {
	*x = CategoryInput{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInput) ProtoMessage() {}

func (x *CategoryInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInput.ProtoReflect.Descriptor instead.
func (*CategoryInput) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ClassifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`                          // 예측 카테고리
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                        // LLM 근거 (1문장)
	ParseOk       bool                   `protobuf:"varint,3,opt,name=parse_ok,json=parseOk,proto3" json:"parse_ok,omitempty"`      // 파싱 성공 여부
	RawOutput     string                 `protobuf:"bytes,4,opt,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"` // parse_ok=false 일 때 LLM 원본 출력 (그 외 빈 문자열)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResult) Reset() {
	*x = ClassifyResult{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResult) ProtoMessage() {}

func (x *ClassifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResult.ProtoReflect.Descriptor instead.
func (*ClassifyResult) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassifyResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ClassifyResult) GetParseOk() bool {
	if x != nil {
		return x.ParseOk
	}
	return false
}

func (x *ClassifyResult) GetRawOutput() string {
	if x != nil {
		return x.RawOutput
	}
	return ""
}

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`             // 분류할 텍스트
	Categories    []*CategoryInput       `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"` // 생략 시 기본 카테고리 사용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ClassifyRequest) GetCategories() []*CategoryInput {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ClassifyResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyResponse) GetResult() *ClassifyResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type BatchClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`           // 분류할 텍스트 목록 (최대 100건)
	Categories    []*CategoryInput       `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"` // 생략 시 기본 카테고리 사용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassifyRequest) Reset() {
	*x = BatchClassifyRequest{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassifyRequest) ProtoMessage() {}

func (x *BatchClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassifyRequest.ProtoReflect.Descriptor instead.
func (*BatchClassifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{4}
}

func (x *BatchClassifyRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *BatchClassifyRequest) GetCategories() []*CategoryInput {
	if x != nil {
		return x.Categories
	}
	return nil
}

type BatchClassifyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	TextPreview   string                 `protobuf:"bytes,2,opt,name=text_preview,json=textPreview,proto3" json:"text_preview,omitempty"` // 입력 텍스트 앞 100자
	Result        *ClassifyResult        `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassifyItem) Reset() {
	*x = BatchClassifyItem{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassifyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassifyItem) ProtoMessage() {}

func (x *BatchClassifyItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassifyItem.ProtoReflect.Descriptor instead.
func (*BatchClassifyItem) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{5}
}

func (x *BatchClassifyItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BatchClassifyItem) GetTextPreview() string {
	if x != nil {
		return x.TextPreview
	}
	return ""
}

func (x *BatchClassifyItem) GetResult() *ClassifyResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type BatchClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Results       []*BatchClassifyItem   `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassifyResponse) Reset() {
	*x = BatchClassifyResponse{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassifyResponse) ProtoMessage() {}

func (x *BatchClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassifyResponse.ProtoReflect.Descriptor instead.
func (*BatchClassifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{6}
}

func (x *BatchClassifyResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchClassifyResponse) GetResults() []*BatchClassifyItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" | "degraded"
	ModelLoaded          bool                   `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	ModelPath            string                 `protobuf:"bytes,3,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"` // 미로드 시 빈 문자열
	DefaultCategoryCount int32                  `protobuf:"varint,4,opt,name=default_category_count,json=defaultCategoryCount,proto3" json:"default_category_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *HealthResponse) GetDefaultCategoryCount() int32 {
	if x != nil {
		return x.DefaultCategoryCount
	}
	return 0
}

var File_proto_classifier_classifier_proto protoreflect.FileDescriptor

const file_proto_classifier_classifier_proto_rawDesc = "" +
	"\n" +
	"!proto/classifier/classifier.proto\x12\n" +
	"classifier\"E\n" +
	"\rCategoryInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"x\n" +
	"\x0eClassifyResult\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\bparse_ok\x18\x03 \x01(\bR\aparseOk\x12\x1d\n" +
	"\n" +
	"raw_output\x18\x04 \x01(\tR\trawOutput\"`\n" +
	"\x0fClassifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x129\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x19.classifier.CategoryInputR\n" +
	"categories\"F\n" +
	"\x10ClassifyResponse\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.classifier.ClassifyResultR\x06result\"g\n" +
	"\x14BatchClassifyRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x129\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x19.classifier.CategoryInputR\n" +
	"categories\"\x80\x01\n" +
	"\x11BatchClassifyItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12!\n" +
	"\ftext_preview\x18\x02 \x01(\tR\vtextPreview\x122\n" +
	"\x06result\x18\x03 \x01(\v2\x1a.classifier.ClassifyResultR\x06result\"f\n" +
	"\x15BatchClassifyResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x127\n" +
	"\aresults\x18\x02 \x03(\v2\x1d.classifier.BatchClassifyItemR\aresults\"\x0f\n" +
	"\rHealthRequest\"\xa0\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12\x1d\n" +
	"\n" +
	"model_path\x18\x03 \x01(\tR\tmodelPath\x124\n" +
	"\x16default_category_count\x18\x04 \x01(\x05R\x14defaultCategoryCount2\xf1\x01\n" +
	"\x11ClassifierService\x12E\n" +
	"\bClassify\x12\x1b.classifier.ClassifyRequest\x1a\x1c.classifier.ClassifyResponse\x12T\n" +
	"\rClassifyBatch\x12 .classifier.BatchClassifyRequest\x1a!.classifier.BatchClassifyResponse\x12?\n" +
	"\x06Health\x12\x19.classifier.HealthRequest\x1a\x1a.classifier.HealthResponseB*Z(issuetracker/internal/classifier/grpc/pbb\x06proto3"

var (
	file_proto_classifier_classifier_proto_rawDescOnce sync.Once
	file_proto_classifier_classifier_proto_rawDescData []byte
)

func file_proto_classifier_classifier_proto_rawDescGZIP() []byte {
	file_proto_classifier_classifier_proto_rawDescOnce.Do(func() {
		file_proto_classifier_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_classifier_classifier_proto_rawDesc), len(file_proto_classifier_classifier_proto_rawDesc)))
	})
	return file_proto_classifier_classifier_proto_rawDescData
}

var file_proto_classifier_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_classifier_classifier_proto_goTypes = []any{
	(*CategoryInput)(nil),         // 0: classifier.CategoryInput
	(*ClassifyResult)(nil),        // 1: classifier.ClassifyResult
	(*ClassifyRequest)(nil),       // 2: classifier.ClassifyRequest
	(*ClassifyResponse)(nil),      // 3: classifier.ClassifyResponse
	(*BatchClassifyRequest)(nil),  // 4: classifier.BatchClassifyRequest
	(*BatchClassifyItem)(nil),     // 5: classifier.BatchClassifyItem
	(*BatchClassifyResponse)(nil), // 6: classifier.BatchClassifyResponse
	(*HealthRequest)(nil),         // 7: classifier.HealthRequest
	(*HealthResponse)(nil),        // 8: classifier.HealthResponse
}
var file_proto_classifier_classifier_proto_depIdxs = []int32{
	0, // 0: classifier.ClassifyRequest.categories:type_name -> classifier.CategoryInput
	1, // 1: classifier.ClassifyResponse.result:type_name -> classifier.ClassifyResult
	0, // 2: classifier.BatchClassifyRequest.categories:type_name -> classifier.CategoryInput
	1, // 3: classifier.BatchClassifyItem.result:type_name -> classifier.ClassifyResult
	5, // 4: classifier.BatchClassifyResponse.results:type_name -> classifier.BatchClassifyItem
	2, // 5: classifier.ClassifierService.Classify:input_type -> classifier.ClassifyRequest
	4, // 6: classifier.ClassifierService.ClassifyBatch:input_type -> classifier.BatchClassifyRequest
	7, // 7: classifier.ClassifierService.Health:input_type -> classifier.HealthRequest
	3, // 8: classifier.ClassifierService.Classify:output_type -> classifier.ClassifyResponse
	6, // 9: classifier.ClassifierService.ClassifyBatch:output_type -> classifier.BatchClassifyResponse
	8, // 10: classifier.ClassifierService.Health:output_type -> classifier.HealthResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_classifier_classifier_proto_init() }
func file_proto_classifier_classifier_proto_init() {
	if File_proto_classifier_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_classifier_classifier_proto_rawDesc), len(file_proto_classifier_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_classifier_classifier_proto_goTypes,
		DependencyIndexes: file_proto_classifier_classifier_proto_depIdxs,
		MessageInfos:      file_proto_classifier_classifier_proto_msgTypes,
	}.Build()
	File_proto_classifier_classifier_proto = out.File
	file_proto_classifier_classifier_proto_goTypes = nil
	file_proto_classifier_classifier_proto_depIdxs = nil
}
