// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: proto/classifier/classifier.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClassifierService_Classify_FullMethodName      = "/classifier.ClassifierService/Classify"
	ClassifierService_ClassifyBatch_FullMethodName = "/classifier.ClassifierService/ClassifyBatch"
	ClassifierService_Health_FullMethodName        = "/classifier.ClassifierService/Health"
)

// ClassifierServiceClient is the client API for ClassifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassifierServiceClient interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	ClassifyBatch(ctx context.Context, in *BatchClassifyRequest, opts ...grpc.CallOption) (*BatchClassifyResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type classifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassifierServiceClient(cc grpc.ClientConnInterface) ClassifierServiceClient {
	return &classifierServiceClient{cc}
}

func (c *classifierServiceClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, ClassifierService_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classifierServiceClient) ClassifyBatch(ctx context.Context, in *BatchClassifyRequest, opts ...grpc.CallOption) (*BatchClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchClassifyResponse)
	err := c.cc.Invoke(ctx, ClassifierService_ClassifyBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classifierServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ClassifierService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifierServiceServer is the server API for ClassifierService service.
// All implementations must embed UnimplementedClassifierServiceServer
// for forward compatibility.
type ClassifierServiceServer interface {
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	ClassifyBatch(context.Context, *BatchClassifyRequest) (*BatchClassifyResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedClassifierServiceServer()
}

// UnimplementedClassifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassifierServiceServer struct{}

func (UnimplementedClassifierServiceServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedClassifierServiceServer) ClassifyBatch(context.Context, *BatchClassifyRequest) (*BatchClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyBatch not implemented")
}
func (UnimplementedClassifierServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedClassifierServiceServer) mustEmbedUnimplementedClassifierServiceServer() {}
func (UnimplementedClassifierServiceServer) testEmbeddedByValue()                           {}

// UnsafeClassifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassifierServiceServer will
// result in compilation errors.
type UnsafeClassifierServiceServer interface {
	mustEmbedUnimplementedClassifierServiceServer()
}

func RegisterClassifierServiceServer(s grpc.ServiceRegistrar, srv ClassifierServiceServer) {
	// If the following call panics, it indicates UnimplementedClassifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassifierService_ServiceDesc, srv)
}

func _ClassifierService_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServiceServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassifierService_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServiceServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassifierService_ClassifyBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServiceServer).ClassifyBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassifierService_ClassifyBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServiceServer).ClassifyBatch(ctx, req.(*BatchClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassifierService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassifierService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassifierService_ServiceDesc is the grpc.ServiceDesc for ClassifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classifier.ClassifierService",
	HandlerType: (*ClassifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _ClassifierService_Classify_Handler,
		},
		{
			MethodName: "ClassifyBatch",
			Handler:    _ClassifierService_ClassifyBatch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ClassifierService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/classifier/classifier.proto",
}
